# Generated by Django 6.0.2 on 2026-03-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
