# Generated by Django 6.0.2 on 2026-03-15 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('devto', 'Dev.to'), ('hashnode', 'Hashnode'), ('stackexchange', 'StackExchange'), ('codeforces', 'Codeforces'), ('orcid', 'ORCID'), ('youtube', 'YouTube')], max_length=50)),
                ('connection_type', models.CharField(choices=[('oauth', 'OAuth'), ('username', 'Username'), ('token', 'Token'), ('public_id', 'Public ID')], max_length=20)),
                ('external_username', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_sources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
