# Generated by Django 6.0.2 on 2026-03-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectedsource',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectedsource',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
