# Generated by Django 6.0.2 on 2026-04-04 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_articleview'),
        ('articles', '0004_alter_article_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleview',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='articles.article'),
        ),
    ]
