# Generated by Django 6.0.2 on 2026-04-14 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_profileview_viewer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_views_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectview',
            name='viewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_views_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='profileview',
            constraint=models.UniqueConstraint(fields=('user', 'viewer'), name='unique_profile_view_per_user'),
        ),
    ]
