# Generated by Django 6.0.2 on 2026-04-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('source', 'external_id')},
        ),
    ]
