# Generated by Django 6.0.2 on 2026-04-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
