# Generated by Django 6.0.2 on 2026-02-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='portfolio_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
