# Generated by Django 6.0.2 on 2026-03-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_portfolio_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
